### ISSUE TITLE
Sourcemaps Take up More Space than Scripts

### ISSUE THREAD

**Issue by Weblors** [floridoo/gulp-sourcemaps#126]
Un-uglified, my scripts are 24 KB, uglified they are 12 KB, and with source-maps they are close to 78 KB. Am I using it wrong? Or is it supposed to be this way or what's going on here?

**Comment by zedd45** [comment]
Since sourcemaps are intended for debugging only, I would externalize your source maps, so they only load if you open dev tools. 

You can do this like so:
` .pipe( sourcemaps.write('./'))`

You can specify any location, simply by providing the path as the argument.   

Here's the related section in the docs:
https://github.com/floridoo/gulp-sourcemaps/tree/v1.5.2#write-external-source-map-files


Alternatively, you could use [gulp if](https://github.com/robrich/gulp-if/) or the like to only generate sourcemaps for development.

**Comment by Weblors** [comment]
Thanks, that helps a lot :)
I kinda feel like an idiot for not having noticed earlier :P

**Comment by zedd45** [comment]
All good! Happens to the best of us! :)
