### ISSUE TITLE
[windows]Literal "\n" is output instead of newline characters

### ISSUE THREAD

**Issue by mredbishop** [floridoo/gulp-sourcemaps#142]
On windows (8.1 if it makes a difference) when I output sourcemaps they include the slash character followed by the letter instead of the newline character. Is this a know issue?

Cheers,

Ed

**Comment by floridoo** [comment]
Is this really the literal characters, or is your editor rendering Unix style line returns as `\n`? I have no Windows computer to test this on.

**Comment by mredbishop** [comment]
Yes, it's really outputting them as \n rather than a newline character. I've opened them in my linux environment too.

**Comment by hzlzh** [comment]
And option to choose `\n` or `\n\n` is needed I think.

**Comment by gluons** [comment]
Same issue.
Show `\n` in file instead of real newline character.

**It actually print text `\n`.**
It isn't `\n` character.

**Comment by nmccready** [comment]
Is this still a problem?

**Comment by nmccready** [comment]
I don't think this is an issue any longer due to [detect-newline](https://github.com/floridoo/gulp-sourcemaps/blob/master/src/utils.js#L27).


If it is still a problem then yes.
@hzlzh is correct
> And option to choose \n or \n\n is needed I think.


This can easily be added to [util.getCommentFormatter](https://github.com/floridoo/gulp-sourcemaps/blob/master/src/utils.js#L24) from [write.js](https://github.com/floridoo/gulp-sourcemaps/blob/master/src/write.js#L95). Feel free to PR it.
