### ISSUE TITLE
Better documentation on how to write gulp-sourcemaps plugin

### ISSUE THREAD

**Issue by ivanwills** [floridoo/gulp-sourcemaps#172]
I'm trying to integrate gulp-sourcemaps to my project but the documentation is somewhat limited. From the doucmentation , the below lines:

```javascript
    // apply source map to the chain 
    if (file.sourceMap) {
      applySourceMap(file, result.map);
    }
```

have the undescribed ```result.map```  there is no hint on how to implement the line or where to get documentation from.

**Comment by floridoo** [comment]
How to generate a source map highly depends on your plugin. If your plugin uses another library for manipulating source code, changes are good that it can also generate a source map. Otherwise you need to generate a source map corresponding to the changes your plugin does to the sources. For more information see e.g.:
- http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/?redirect_from_locale=it
- https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit
