### ISSUE TITLE
.write() is appending a new line when using loadMaps:true

### ISSUE THREAD

**Issue by devamora** [floridoo/gulp-sourcemaps#222]
`return gulp.src('source/**/*.js')
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(sourcemaps.write('../../../tests-tmp'))
    .pipe(gulp.dest('source'));`

I'm trying to write the sourcemaps path for all my js files but I realised it was appending the path every the write function was called. 
Then I've started using loadMaps:true and this is writing the paths only in the files that had no sourcemap before, but write function is appending a new line at the end of my js files.

**Comment by nmccready** [comment]
Please try against master and see if this is still an issue. Will re-open depending on feedback.

**Comment by devamora** [comment]
Upgraded to version 1.7.3 and still having the issue.

To be more clear, after running the gulp piped command I've posted before I can have to options: 

- File with no sourcemap link at the end of the file: this works perfectly appending the sourcemap link + new extra line.

- File with sourcemap link at the end of the file: it's like removing the link and appending it again with an extra new line, which causes a file change for git :(

**Comment by nmccready** [comment]
I think this is expected behavior with accordance to how things are currently designed:

Write is called multiple times.
- https://github.com/floridoo/gulp-sourcemaps/blob/master/test/write.js#L537

If it is already inlined it is removed.
- https://github.com/floridoo/gulp-sourcemaps/blob/master/test/init.js#L180-L188

Your piping every file through and calling write on each.

Your best bet to help us get a better understanding of you problem is to copy one of the existing specs and make a file called test/initWrite.js . Then in there write the test with your expected behavior. Then we can meet you halfway and try to make the test pass.

**Comment by nmccready** [comment]
I guess an option to remove the extra line would possibly resolve your issue. I wonder if the extra line is necessary anyways.

**Comment by nmccready** [comment]
I think there are some possible routes to fix this, but it will involve more options and or some loadMap detection in the write function itself.

`commentFormatter` could be come a option to specify your own custom formatting
- https://github.com/floridoo/gulp-sourcemaps/blob/master/index.js#L297-L298

By not including the newline there only gets you half way as you want them for files that do not already contain maps.

In `init` you can also try the `largeFiles` option as it does not remove the comments. However I think you might get the newline still and posisbly dupe comments. Try it out to verify.

https://github.com/floridoo/gulp-sourcemaps/blob/master/index.js#L53-L54

**Comment by devamora** [comment]
Ok I will make this test as soon as possible.

Anyway, I understand that the new line is necessary. But running a write() twice on a file, becames a "new line + new line + link" and if you run it 3 times "new line + new line + new line + link", etc (which makes git to see changes on eeevery source file :) )

Maybe the problem is that I'm running .write every time I run the tests and I should use it in a different way.

**Comment by nmccready** [comment]
@devamora I think this is achievable if we make a tag on the sourceMap object to signify that it originally had a sourcemap to begin with. Therefore if this flag exists then we don't add the newline.

**Comment by nmccready** [comment]
@devamora I worked on this a [little](https://github.com/floridoo/gulp-sourcemaps/compare/master...realtymaps:preExistingSourceMapFormatting?expand=1) it is not done. But this is what I am thinking. One thing that kinda sucks is `convert-source-map` does not give me access to their regexes. That way we could get the original sourcemap comment and save it off instead of stripping it. 
This makes me wonder why we are stripping the comments anyway.

**Comment by nmccready** [comment]
@devamora PR'd #255

**Comment by devamora** [comment]
Thank you @nmccready about being working on it!!

**Comment by nmccready** [comment]
@devamora did you try out the PR, im gonna merge it

**Comment by devamora** [comment]
@nmccready Yes, once the sourcemap is appended is not modifying the file anymore :)
