### ISSUE TITLE
"engines" is not defined in package.json

### ISSUE THREAD

**Issue by catdad** [floridoo/gulp-sourcemaps#249]
Defining this allows older version of Node to not download and accept new versions of the lib. In reality, the major 2 release should have defined this, as it targets 4.x and above directly.

https://docs.npmjs.com/files/package.json#engines

I am not totally sure what a good retroactive solution to this would be, but still... something to think about.

**Comment by nmccready** [comment]
I am not worried about the resolution of renaming / bumping versions as they are technically compatible with what they are relative to support. So adding these flags will just make it safer from hurting one's self. So yes 2.0 should work with node >= 4.X  and 1.X should be >= 0.10.X . Feel free to PR.

**Comment by catdad** [comment]
The issue here is that you know 2.0 supports Node 4.x, but NPM doesn't know that, and it will install the new version on old Node anyway. So if I am using Node 0.12 and run `npm install gulp-sourcemaps`, it will install the latest 2.x version. With `engines`, it will know better and pull down the latest 1.x instead.

A problem with doing this now is that even if `engines` is included in the next release (2.1.2), NPM will still think 2.1.1 is fine and install it.

**Comment by nmccready** [comment]
Ok, so what is your resolution? I don't see worrying about the past versions being that big of a deal.  Make a PR and we can move forward in the right direction. 

So are you suggesting bumping versions to 2.2 and 1.9? Is there a dilemma that there is not more version space where 1.X would ideally be bumped to 2, and 2 to 3? 

I am trying to figure out why were dwelling on the issue here and not just issuing a PR.

**Comment by nmccready** [comment]
master:
https://github.com/floridoo/gulp-sourcemaps/commit/ec9b51d0bb88746e16f85479f12f8cfbd7ed159a

1.X:
https://github.com/floridoo/gulp-sourcemaps/commit/02908271ef2e9c04c2a322f9d629a5264f88c794
