### ISSUE TITLE
Problem with gulp-sass ? Or gulp-autoprefixer ? Or gulp-sourcemaps ?

### ISSUE THREAD

**Issue by ByScripts** [floridoo/gulp-sourcemaps#60]
Hi,

There is a lot of issue about mixing gulp-sass and/or gulp-autoprefixer with gulp-sourcemaps.

For example : https://github.com/dlmanning/gulp-sass/issues/106, https://github.com/sindresorhus/gulp-autoprefixer/issues/8

I just spend 2 hours debugging to find out where the problem come from, and still no success.

But I finally noticed something (but still don't know where the problem come from).

In [source-map-generator.js @ Line 359](https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-generator.js#L359), I watched the `key` value.

In this configuration:

```js
gulp.task('css', function () {
    gulp.src('./assets/sass/style.scss')
        .pipe(sourcemaps.init())
        .pipe(sass())
        //.pipe(sourcemaps.write({includeContent: false}))
        //.pipe(sourcemaps.init({loadMaps: true}))
        .pipe(autoprefixer())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./public/css'))
});
```

The value of the key is `$style.css`, and it does **not** work

But in this configuration:

```js
gulp.task('css', function () {
    gulp.src('./assets/sass/style.scss')
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(sourcemaps.write({includeContent: false}))
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(autoprefixer())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./public/css'))
});
```

The value of the key is `$style.scss`, and it works

Because with the two configurations, `_sourcemapContents` in [source-map-generator.js#360](https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-generator.js#L359) has always a `$style.scss` key.

Hope this helps to resolve this issue, and to find if the problem come from sourcemap, sass or autoprefixer (or something else)

**Comment by polarathene** [comment]
I'm not sure if I'm having the same problem. I've been looking into this for about 2 days now. I think gulp-autoprefixer is making a correct sourcemap between it's input/output css files. gulp-sourcemaps and gulp-sass don't seem to be the issue either. I've tried compiling my scss file with node-sass and it's sourcemap feature, it seems to output a broken sourcemap regardless of settings.

I've come across an excellent visualizer tool. It would seem that the mappings for the scss file are correct but the output css file is incorrect, everything maps to 0. So the issue is likely node-sass or libsass?

You can see the scss/css I've been using to learn the gulp-sass/autoprefixer workflow with sourcemaps in the visualizer tool [here](http://sokra.github.io/source-map-visualization/#base64,LnRoaW5nIHsKICBmaWx0ZXI6IHNlcGlhKDEpOwogIGNvbG9yOiAjM2JiZmNlOyB9CgouYm9vdHMgewogIGZpbHRlcjogc2VwaWEoMSk7CiAgY29sb3I6ICNhMjI7IH0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXdvSkluWmxjbk5wYjI0aU9pQXpMQW9KSW1acGJHVWlPaUFpZUcxaGFXNHVZM056SWl3S0NTSnpiM1Z5WTJWeklqb2dXd29KQ1NKdFlXbHVMbk5qYzNNaUNnbGRMQW9KSW5OdmRYSmpaWE5EYjI1MFpXNTBJam9nV3dvSkNTSWtZbXgxWlRvZ0l6TmlZbVpqWlR0Y2NseHVKSEpsWkRvZ0kyRXlNanRjY2x4dVhISmNibHh5WEc0dWRHaHBibWQ3SUdacGJIUmxjam9nYzJWd2FXRW9NU2s3SURzZ1kyOXNiM0k2SkdKc2RXVTdmVnh5WEc1Y2NseHVMbUp2YjNSemUxeHlYRzRnSUdacGJIUmxjam9nYzJWd2FXRW9NU2s3WEhKY2JpQWdZMjlzYjNJNklDUnlaV1E3WEhKY2JuMGlDZ2xkTEFvSkltMWhjSEJwYm1keklqb2dJa0ZCU1VFc1FVRkJVU3hCUVVGUkxFRkJRVmtzUVVGS2NrSXNRVUZOVUN4QlFVTkZMRUZCUVZFc1FVRkRVaXhCUVZCSklpd0tDU0p1WVcxbGN5STZJRnRkQ24wPSAqLw==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieG1haW4uY3NzIiwic291cmNlcyI6WyJtYWluLnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiJGJsdWU6ICMzYmJmY2U7XHJcbiRyZWQ6ICNhMjI7XHJcblxyXG5cclxuLnRoaW5neyBmaWx0ZXI6IHNlcGlhKDEpOyA7IGNvbG9yOiRibHVlO31cclxuXHJcbi5ib290c3tcclxuICBmaWx0ZXI6IHNlcGlhKDEpO1xyXG4gIGNvbG9yOiAkcmVkO1xyXG59Il0sIm1hcHBpbmdzIjoiQUFJQSxBQUFRLEFBQVEsQUFBWSxBQUpyQixBQU1QLEFBQ0UsQUFBUSxBQUNSLEFBUEkiLCJuYW1lcyI6W119,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw0KDQoNCi50aGluZ3sgZmlsdGVyOiBzZXBpYSgxKTsgOyBjb2xvcjokYmx1ZTt9DQoNCi5ib290c3sNCiAgZmlsdGVyOiBzZXBpYSgxKTsNCiAgY29sb3I6ICRyZWQ7DQp9) . Note the bottom content identifying the mappings, each mapping starts with 0->, and as you can see in the css content on the right, it's highlighting the first line only. Am I the only one getting a result like this? (autoprefixer aside).

**Comment by polarathene** [comment]
I've looked further into this and am pretty sure the issue is related to libsass or node-sass with how they're producing a sourcemap. I've manually corrected the scss-css sourcemap mappings, then used gulp-autoprefixer, mappings appear to be working and chrome/firefox dev tools are reporting the correct lines to the scss. You can see the scss/autoprefixer sourcemap [here](http://sokra.github.io/source-map-visualization/#base64,LnRoaW5nIHsKICAtd2Via2l0LWZpbHRlcjogc2VwaWEoMSk7CiAgICAgICAgICBmaWx0ZXI6IHNlcGlhKDEpOwogIGNvbG9yOiAjM2JiZmNlOyB9CgouYm9vdHMgewogIC13ZWJraXQtZmlsdGVyOiBzZXBpYSgxKTsKICAgICAgICAgIGZpbHRlcjogc2VwaWEoMSk7CiAgY29sb3I6ICNhMjI7IH0KCgovKiMgc291cmNlTWFwcGluZ1VSTD14bWFpbi5jc3MubWFwICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3Njc3MvbWFpbi5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUlBO0VBQVEsMEJBQVE7VUFBUixrQkFBUTtFQUFVLGdCQUpuQixFQUFBOztBQU1QO0VBQ0UsMEJBQVE7VUFBUixrQkFBUTtFQUNSLGFBUEksRUFBQSIsImZpbGUiOiJ4bWFpbi5jc3MiLCJzb3VyY2VSb290IjoiLi4vIn0=,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw0KDQoNCi50aGluZ3sgZmlsdGVyOiBzZXBpYSgxKTsgY29sb3I6JGJsdWU7fQ0KDQouYm9vdHN7DQogIGZpbHRlcjogc2VwaWEoMSk7DQogIGNvbG9yOiAkcmVkOw0KfQ==)

Raised an issue on node-sass [here](https://github.com/sass/node-sass/issues/619), and just been notified it's an issue with libsass which should be solved with libsass 3.2.

**Comment by DallanQ** [comment]
Thank-you @ByScripts, your solution worked great for me! (I'm using gulp-sass)

**Comment by polarathene** [comment]
@ByScripts `gulp-sass` was updated recently, mappings aren't broken like before. If you're using `gulp-ruby-sass` you should be fine with the alpha release if using external sources, embedded don't seem to work. The only other issue with `gulp-ruby-sass` that prevents me using it is the file paths placed in `sources` of the sourcemap, I think this is only an issue with windows from what I've read.

I have code examples for both [here](https://github.com/sindresorhus/gulp-autoprefixer/issues/10#issuecomment-69910254)

**Comment by swieder227** [comment]
`npm update gulp-sass` fixed the problem for me. Now working with `gulp-sass`, `gulp-autoprefixer`, and `gulp-sourcemaps`.
```
gulp.task('styles', function() {
  return gulp.src('scss/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass({ style: 'expanded' }))
    .pipe(autoprefixer('last 2 version'))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('css'))
    .pipe(rename({suffix: '.min'}))
    .pipe(minifycss())
    .pipe(gulp.dest('css'))
    .pipe(connect.reload())
    .pipe(notify({ message: 'Styles task complete' }));
});
```

**Comment by heikki** [comment]
I think this can be closed. @ByScripts's [sample tasks](https://github.com/ByScripts/gulp-sample/blob/master/gulpfile.js) work identically with latest module versions.

**Comment by stevemao** [comment]
I don't think having `.pipe(sourcemaps.write({includeContent: false}))
        .pipe(sourcemaps.init({loadMaps: true}))` in between `sass` and `autoprefixer` is elegant.

**Comment by heikki** [comment]
@stevemao Then remove them :smile: Both tasks work now.

**Comment by stevemao** [comment]
Thanks @heikki , for the reference web-starter-kit is already using this.

https://github.com/google/web-starter-kit/commit/8c356e1bb9bbd5218ec533780b035beb6d9b035e

**Comment by Tibicenas** [comment]
Hi, i was reading that the new version fixed the problem, but i installed **today**  
  "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-sass": "^2.3.1",
    "gulp-sourcemaps": "^1.6.0",

And doesn't work if i do:
```javascript
gulp.task('sass', () => {
  log('Compiling SCSS files...');
  return gulp
    .src('./src/app/**.*scss')
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(autoprefixer({ browser: ['last 2 version', '> 5%'] }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./.temp/'));
});
```

But if i added the @ByScripts **two MAGIC LINES** works
```javascript
// THIS WORKS
gulp.task('sass', () => {
  log('Compiling SCSS files...');
  return gulp
    .src('./src/app/**.*scss')
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(sourcemaps.write({includeContent: false}))
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(autoprefixer({ browser: ['last 2 version', '> 5%'] }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./.temp/'));
});
```

When this would be fixed to don't need that two lines... is like zero readable... :S

**Comment by shamseerahammedm** [comment]
was facing the same issue, solutions by @HectorLS  solved my prob.

**Comment by sizzlorr** [comment]
@HectorLS solution helped me too, but here
`.pipe(autoprefixer({ browser: ['last 2 version', '> 5%'] }))` 
must be browserS

**Comment by manorossa** [comment]
I had the same problem (autoprefixer not working), and the solution by @HectorLS didn't work for me. But what did work, was commenting out my lines implementing sourcemaps; then running my gulp task (which then allowed autoprefixer to work).
After that I was able to reinstate my sourcemaps config and they both worked nicely together.
Hope that might help someone.

**Comment by joffff** [comment]
@manorossa Could you share an example of your code?

**Comment by FrancescoColonna** [comment]
Upgrading to **2.6.4** the problem does not persists anymore.
This is my task
`function sass () {
    const processors = [cachebuster({
        cssPath: `/dist/stylesheets`, imagesPath: `/dist/img`
    }), rucksack];

    return gulp.src('src/stylesheets/main.scss')
               .pipe($.sourcemaps.init())
               .pipe($.sass({includePaths: PATHS.sass}).on('error', $.sass.logError))
               .pipe($.autoprefixer({browsers: COMPATIBILITY}))
               .pipe($.if(PRODUCTION, $.cleanCss({compatibility: '*'})))
               .pipe(postcss(processors))
               .pipe($.if(!PRODUCTION, $.sourcemaps.write('.')))
               .pipe(gulp.dest(PATHS.dist + '/stylesheets'))
               .pipe(browser.reload({stream: true}))
               .pipe(notify({message: 'Css compilato correttamente', onLast: true}));
}`

**Comment by Alecto** [comment]
doesnt work
    .pipe($.autoprefixer({ browsers: ['last 5 versions', '> 1%'], cascade: true }))
